name: "Test"
on:
  pull_request:
  push:
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: brew install macfuse
    - run: nix-shell
